#!/usr/bin/env python3
"""
render_captions.py — burn the caption cards onto the video with Remotion.

    python3 stages/03_render/scripts/render_captions.py <run-slug>

This is the last mile. It runs locally, needs no editor open, and produces the
file that gets posted.

WHAT IT DOES NOT DO. It does not decide anything about how captions look. Every
constant — size, weight, colour, the anchor, the line cap, the shadow — is read
out of `_config/edit-defaults.yaml` here and handed to Remotion as props. The
React side has no defaults of its own worth the name. Two reasons that matters:

  - The line cap and the font are a matched pair. `chars_per_line_derived` was
    computed from Inter SemiBold's character advance. If the renderer chose its
    own font, the wrapping done by chunk_captions.py would no longer describe
    the pixels, and the longest lines — the ones most likely to be cropped —
    would be the ones that overflowed.
  - A caption style that drifts from the config is invisible in any single
    video. You only catch it by putting two side by side, months apart.

THE GEOMETRY IS ASSERTED BEFORE ANYTHING RENDERS, because a render takes minutes
and a breach of the safe zone is not visible in a progress bar — it is visible
once, on the phone, after the wait.
"""

from __future__ import annotations

import base64
import json
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))
import pipeline_lib as lib  # noqa: E402

REMOTION_DIR = lib.ROOT / "remotion"
COMPOSITION = "CaptionedVideo"


def source(run: Path) -> dict:
    """
    The video the transcript was taken from, with its duration and frame rate.

    All three are read from 01-transcript.json rather than probed again here.
    The recorded numbers are what the caption timings were built against, so a
    second probe could only introduce a disagreement — and a frame rate that
    disagrees with the one the cards were timed to is exactly how captions drift.
    """
    transcript = lib.read_json(lib.require(run / "01-transcript.json", "transcribe.py"))
    path = Path(transcript["video"])

    if not path.exists():
        # THE LEVELLED COPY IS MEANT TO BE DELETABLE. output/audio/ fills with
        # full-size video and is git-ignored, so it WILL get cleared — and
        # without this, re-rendering would stop at a file the person removed on
        # purpose. The original export is recorded separately in 01-video.md,
        # which is exactly the file that survives a clear-out.
        sys.path.insert(0, str(lib.ROOT / "stages" / "01_ingest" / "scripts"))
        from read_video import read_record  # noqa: E402
        original = read_record(run)["path"]
        if original.exists():
            print(f"  source      {path.name} is gone — falling back to "
                  f"{original.name}")
            print("              (the levelled copy was cleared; re-run "
                  "calibrate_audio.py to get it back)")
            path = original
        else:
            sys.exit(f"the source video has moved or been deleted:\n    {path}")

    return {"path": path, "duration": transcript["duration"], "fps": transcript["fps"]}


def write_font_module() -> Path:
    """
    Embed Inter SemiBold into the bundle as a data URI, so the renderer never
    fetches it.

    IT WAS FETCHED OVER HTTP AND THAT IS WHAT BROKE LONG RENDERS. Under render
    concurrency the request to Remotion's static server could simply hang; the
    font handle stayed open, and the render died reporting a font timeout at
    whatever frame it had reached. A two-minute take failed three different ways
    at three different frames before the cause was clear, while every short test
    passed because it finished before the timer ran out.

    A data URI has nothing to queue behind and nothing to time out. The .ttf on
    disk stays the single source — this file is generated from it every render
    and is not tracked.
    """
    ttf = REMOTION_DIR / "public" / "fonts" / "Inter-SemiBold.ttf"
    lib.require(ttf, "the repository — Inter SemiBold is tracked, not downloaded")
    encoded = base64.b64encode(ttf.read_bytes()).decode("ascii")
    module = REMOTION_DIR / "src" / "font-data.ts"
    module.write_text(
        "// GENERATED by render_captions.py from public/fonts/Inter-SemiBold.ttf.\n"
        "// Do not edit, and do not commit. Change the .ttf instead.\n"
        f'export const INTER_SEMIBOLD = "data:font/ttf;base64,{encoded}";\n',
        encoding="utf-8",
    )
    print(f"  font        Inter SemiBold embedded ({len(encoded) / 1024:.0f} KB, no fetch)")
    return module


def stage(video: Path, public: Path, slug: str) -> Path:
    """
    Put the video where Remotion can serve it, in a codec Chromium can decode.

    Copied rather than linked: a link the bundler declines to follow fails in a
    way that is hard to see from here.

    TRANSCODED WHEN IT IS NOT H264. An iPhone shoots HEVC by default, and
    Chromium cannot decode it. The failure is the worst kind — not a rejection
    but a stall, surfacing minutes later as a font timeout at whatever frame the
    renderer reached, which says nothing about the codec. So it is converted
    here, once, and the reason is printed.

    Only the picture is re-encoded, and only to feed the renderer. Nothing about
    the caption timings depends on it: they were built from the transcript, and
    the transcript was taken from your original file, which is not touched.
    """
    codec = lib.probe_codec(video)
    staged = public / f"{slug}.mp4"

    if codec == "h264":
        if not staged.exists() or staged.stat().st_size != video.stat().st_size:
            print(f"  staging     {video.name} -> remotion/public/")
            shutil.copy2(video, staged)
        return staged

    if staged.exists() and staged.stat().st_mtime > video.stat().st_mtime:
        print(f"  staging     {staged.name} already converted from {codec}")
        return staged

    print(f"  staging     {video.name} is {codec}, which the renderer cannot decode")
    print(f"              converting to h264 — once, and only for the render")
    result = subprocess.run(
        [
            "ffmpeg", "-v", "error", "-y", "-i", str(video),
            "-c:v", "libx264", "-preset", "veryfast", "-crf", "18",
            "-pix_fmt", "yuv420p",
            "-c:a", "aac", "-b:a", "192k",
            str(staged),
        ],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        staged.unlink(missing_ok=True)   # never leave a half-written file to be reused
        sys.exit(f"could not convert {video.name} from {codec}:\n{result.stderr.strip()}")
    print(f"              converted, {staged.stat().st_size / 1e6:.0f} MB")
    return staged


def assert_geometry(cfg: dict) -> None:
    geometry, typography, caption = cfg["geometry"], cfg["typography"], cfg["caption"]
    canvas_h = geometry["canvas"][1]
    block_h = typography["caption_size_px"] * 1.3 * caption["max_lines"]
    block_bottom = geometry["anchor_fraction"] * canvas_h + block_h / 2
    if block_bottom > geometry["bottom_limit_px"]:
        sys.exit(
            f"caption geometry breaches the safe zone: a {caption['max_lines']}-line "
            f"card at anchor {geometry['anchor_fraction']} runs to y={block_bottom:.0f}, "
            f"past the usable floor of {geometry['bottom_limit_px']}.\n"
            "  Lower the anchor or the font size in _config/edit-defaults.yaml."
        )
    if typography["caption_size_px"] < typography["legibility_floor_px"]:
        sys.exit(
            f"caption size {typography['caption_size_px']}px is below the legibility "
            f"floor of {typography['legibility_floor_px']}px. Nothing renders below it."
        )
    print(f"  geometry    block bottom y={block_bottom:.0f} "
          f"(floor {geometry['bottom_limit_px']}) — clears")


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: render_captions.py <run-slug>")
    slug = sys.argv[1]
    run = lib.run_dir(slug)

    if not (REMOTION_DIR / "node_modules").is_dir():
        sys.exit(
            "Remotion is not installed.\n"
            "  cd remotion && npm install"
        )

    cards_data = lib.read_json(lib.require(run / "02-caption-cards.json", "chunk_captions.py"))
    cards = cards_data["cards"]
    if not cards:
        sys.exit("there are no caption cards to render.")

    cfg = lib.rules()
    # Pacing overrides in memory/preferences.md already shaped the cards; the
    # style is read fresh so a typography change takes effect on a re-render
    # without re-chunking.
    assert_geometry(cfg)
    write_font_module()

    media = source(run)
    video, fps, duration = media["path"], media["fps"], media["duration"]
    width, height = cfg["geometry"]["canvas"]

    public = REMOTION_DIR / "public"
    public.mkdir(parents=True, exist_ok=True)
    staged = stage(video, public, slug)

    typography, geometry = cfg["typography"], cfg["geometry"]
    props = {
        "videoSrc": staged.name,
        "cards": cards,
        "style": {
            "fontFamily": typography["font_family"],
            "fontWeight": typography["caption_weight"],
            "fontSizePx": typography["caption_size_px"],
            "colour": typography["colour"],
            "anchorFraction": geometry["anchor_fraction"],
            "centreXPx": geometry["centre_x"],
            "maxLineWidthPx": geometry["max_line_width_px"],
            "lineHeightEm": 1.3,
            "shadow": typography["shadow"],
            "uppercase": typography["case"] == "upper",
        },
        "meta": {
            "width": width,
            "height": height,
            "fps": fps,
            # Ceil, so a final part-frame is not dropped. A truncated last frame
            # is how the end of a sentence goes missing.
            "durationInFrames": int(-(-duration * fps // 1)),
        },
    }

    props_path = run / "03-remotion-props.json"
    lib.write_json(props_path, props)

    out_dir = Path(lib.load_paths()["render_output"]).expanduser()
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"{slug}.mp4"

    print(f"  video       {video.name}  {lib.timecode(duration)} @ {fps:.3f}fps")
    print(f"  captions    {len(cards)} cards, {typography['font_family']} "
          f"{typography['caption_weight']} at {typography['caption_size_px']}px")
    print(f"  canvas      {width}x{height}")
    print(f"  rendering   -> {out_file}")

    result = subprocess.run(
        [
            "npx", "remotion", "render", "src/index.ts", COMPOSITION,
            str(out_file),
            f"--props={props_path}",
        ],
        cwd=str(REMOTION_DIR),
    )
    if result.returncode != 0:
        sys.exit(
            f"\n  Remotion exited {result.returncode}. Nothing was written.\n"
            f"  The props it was given are in {lib.RUNS_REL}/{slug}/03-remotion-props.json —\n"
            "  you can reproduce this exactly with:\n"
            f"    cd remotion && npx remotion studio src/index.ts"
        )

    print(f"\n  done        {out_file}")
    print("  The safe zone is a conservative envelope, not a published spec —")
    print("  check the first export on the phone, in both apps, before trusting it.")


if __name__ == "__main__":
    main()
